version: "3"

services:
  rabbitmq:
    # image: rabbitmq:3.11-management-alpine
    image: rabbitmq:3.11-alpine
    ports:
      - "5672:5672"
    deploy:
      mode: replicated
      replicas: 1
    # environment:
    #   - RABBITMQ_DEFAULT_USER=guest
    #   - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq